### ISSUE TITLE
Consistency for /data-sources

### ISSUE THREAD

**Issue by docktermj** [Senzing/rest-api-proposal#6]
When viewing [senzing-api.yaml in an editor](http://editor.swagger.io/?url=https://raw.githubusercontent.com/Senzing/rest-api-proposal/bc642e988b9e64b2781195f7ab9d60ad1059253b/senzing-api.yaml), I see that `/data-sources` operates in the capacity of configuration, but other `/data-sources/...` URIs manage entities.

I wasn't expecting that.

**Comment by barrycaceres** [comment]
It seemed natural to have /data-sources return a list of configured data sources, but to have /data-sources/{dataSourceCode}/records/{recordId} return a record from that data sources.

We can group endpoints however we like in YAML regardless of the path hierarchy.

I think trying to make artificial path hierarchies like:

/config/data-sources

/data/data-sources/{dataSourceCode}/records/{recordId}

Would be awkward.
