### ISSUE TITLE
Add the ability to load records to the API

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/rest-api-proposal#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by barrycaceres** [comment]
Need to be able to use PUT and POST operations to load one or more records for a data source.

**Comment by docktermj** [comment]
Pull requests

1. https://github.com/Senzing/senzing-rest-api/pull/8
